version: '3.8'
services:
  db:
    image: mysql
    container_name: "mysql_tfs"
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1
    environment:
      - MYSQL_ROOT_HOST="%"
      - MYSQL_DATABASE=tfs
      - MYSQL_USER=tfs
      - MYSQL_PASSWORD=tfs
    volumes:
      - ./db-volume:/var/lib/mysql
    ports:
      - 3306:3306
  
  tfs:
    image: giorox/angelion-tfs:1.0.0
    container_name: "server_tfs"
    restart: on-failure
    ports:
      - "7171:7171"
      - "7172:7172"
    depends_on:
      - db
    volumes:
      - .:/srv
      - "./config.lua:/srv/config.lua"
      - "./key.pem:/srv/key.pem"

