version: '3.8'
services:
  db:
    image: mysql
    container_name: "mysql_tfs"
    restart: unless-stopped
    command: --log_bin_trust_function_creators=1
    tty: true
    environment:
      - MYSQL_ROOT_HOST="%"
      - MYSQL_DATABASE=tfs
      - MYSQL_USER=tfs
      - MYSQL_PASSWORD=tfs
      - MYSQL_ALLOW_EMPTY_PASSWORD=true 
    volumes:
      - ./db-volume:/var/lib/mysql  # Where data is store in MySQL
      - ./schema:/docker-entrypoint-initdb.d  # Where SQL files shoulds be stored to import a schema
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s
  
  tfs:
    image: giorox/tfs-ubuntu:1.0.0
    container_name: "server_tfs"
    restart: on-failure
    tty: true
    ports:
      - "7171:7171"
      - "7172:7172"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/srv
      - "./config.lua:/srv/config.lua"
      - "./key.pem:/srv/key.pem"

